# Generated by Django 3.1.7 on 2021-04-26 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210415_1410'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterUniqueTogether(
            name='substitution',
            unique_together={('user_id', 'substitution_id')},
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='product_id',
        ),
    ]
