# Generated by Django 3.1.7 on 2021-04-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210426_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substitution',
            old_name='substitution_id',
            new_name='substitution',
        ),
        migrations.RenameField(
            model_name='substitution',
            old_name='user_id',
            new_name='user',
        ),
    ]
