# Generated by Django 3.1.7 on 2021-05-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210506_1601'),
        ('account', '0003_auto_20210428_2110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='substitution',
            unique_together={('user_id', 'substitution_id')},
        ),
    ]
