language: python
python:
  - '3.6.9'

before_script:
  - pip install -r requirements.txt
  - export $(cat env_travis | xargs)

env: DJANGO_SETTINGS_MODULE="purbeurre.settings"

services:
  - postgresql

script:
  - python3 manage.py test
  