language: python
python:
  - '3.5'

before_script:
  - pip install -r requirements.txt
  - export $(cat env_travis | xargs)

env: DJANGO_SETTINGS_MODULE="purbeurre.settings"

services:
  - postgresql

script:
  - ./manage.py test