language: python
python:
  - '3.6.9'

before_script:
  - pip install -r requirements.txt
  - export $(cat env_travis | xargs)
  - export SECRET_KEY=$(python3 -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())')

env: DJANGO_SETTINGS_MODULE="purbeurre.settings"

services:
  - postgresql

script:
  - python3 manage.py test
