language: python
python:
  - '3.6.9'

before_script:
  - pip install -r requirements.txt

env:
  - DJANGO_SETTINGS_MODULE="purbeurre.settings.travis"
  global:
    - MOZ_HEADLESS=1

addons:
  firefox: lastest

services:
  - postgresql

script:
  - python3 manage.py test
