# Generated by Django 3.1.7 on 2021-04-10 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=150)),
                ('quantity', models.CharField(max_length=100)),
                ('nutriscore', models.CharField(max_length=1)),
                ('energy_kcal_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fat_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('saturated_fat_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbohydrates_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sugars_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fiber_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proteins_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salt_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('energy_kcal_100g_unit', models.CharField(max_length=10)),
                ('fat_100g_unit', models.CharField(max_length=10)),
                ('saturated_fat_100g_unit', models.CharField(max_length=10)),
                ('carbohydrates_100g_unit', models.CharField(max_length=10)),
                ('sugars_100g_unit', models.CharField(max_length=10)),
                ('fiber_100g_unit', models.CharField(max_length=10)),
                ('proteins_100g_unit', models.CharField(max_length=10)),
                ('salt_100g_unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='search.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='search.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('product', 'category'), name='product-categorised'),
        ),
    ]
